#!/usr/bin/env bash
# add release notes
open https://github.com/bees-hive/elegant-git/releases/new
# update formulae
TAG=$(git describe)
COMMIT=$(git log --pretty=%H -1)

if type brew >/dev/null 2>&1 ; then
    info-text "Updating Homebrew formulae..."
    brew bump-formula-pr --no-audit --tag=${TAG} --revision=${COMMIT} elegant-git
else
    error-text "brew binary is not available."
    error-text "Please make a manual formulae update."
    cat <<MESSAGE
Instructions:

    open       https://github.com/bees-hive/homebrew-hive/blob/master/Formula/elegant-git.rb
    update
        git tag:     ${TAG}
        git commit:  ${COMMIT}
MESSAGE
fi
