architect: extsoft
docker:
    image: extsoft/rultor-runtime:r24b04p0g2
    as_root: true
merge:
    fast-forward: only
    rebase: true
    script: ./run-tests
release:
    script: |-
        echo "Release ${tag}"
        bats --tap src/test
