architect: extsoft
docker:
    image: beeshive/elegant-git-ci:3
    as_root: true
merge:
    fast-forward: only
    rebase: true
    script: ./quality-pipeline.bash testing
release:
    script: |-
        ./quality-pipeline.bash testing
        echo "Release ${tag}"
