architect: extsoft
docker:
    image: extsoft/elegant-git-ci:1
    as_root: true
merge:
    fast-forward: only
    rebase: true
    script: ./run-tests
release:
    script: |-
        echo "Release ${tag}"
        bats --tap src/test
