name:                elegant-git
version:             1.0.0
github:              "bees-hive/elegant-git"
license:             MIT
author:              "Dmytro Serdiuk"
maintainer:          "dmytro.serdiuk@gmail.com"
copyright:           "2017 Dmytro Serdiuk"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          Elegant Git is an assistant who carefully automates routine work with Git. See more on <https://elegant-git.bees-hive.org/>

dependencies:
- base >= 4.7 && < 5

- universum
- string-qq
- exceptions
- text
- safe-exceptions
- fmt
- transformers
- mtl
- free
- dlist
- containers
- unordered-containers
- microlens
- microlens-mtl
- microlens-th
- utility-ht
- unliftio

- optparse-applicative
- typed-process

default-extensions:
- FlexibleContexts
- OverloadedStrings
- TypeApplications
- NoImplicitPrelude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Werror=incomplete-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  git-elegant:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elegant-git

tests:
  elegant-git-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elegant-git
    - hspec
