#!/usr/bin/env bash
set -e

source ./libexec/plugins/text

bash_5_0_17=5.0.17
python_3_8_3=3.8.3

eg_docker_organization=beeshive
eg_documents_repository=${eg_docker_organization}/elegant-git-docs-workflows
eg_documents_image=${eg_documents_repository}:python${python_3_8_3}-bash${bash_5_0_17}
WORKER_IMAGE=${eg_docker_organization}/elegant-git-ci:5

# docs workflows
prepare-docs-worker() {
    local bashversion=${bash_5_0_17}
    local pythonversion=${python_3_8_3}
    docker build --tag ${eg_documents_image} \
                 --label bashversion=${bashversion} \
                 --label pythonversion=${pythonversion} \
                 --build-arg bashversion=${bashversion} \
                 --build-arg pythonversion=${pythonversion} \
                 --file .workflows/docs/Dockerfile .
}

publish-docs-worker() {
    info-text "Select image to push:"
    select tag in $(docker image ls --filter reference=${eg_documents_repository} --format "{{.Repository}}:{{.Tag}}"); do
        docker push ${tag}
        break
    done
}

generate-docs() {
    docker run --interactive --rm \
               --mount type=bind,source=$(pwd),target=/elegant-git \
               ${eg_documents_image} generate
}

preview-docs() {
    { sleep 5 && open http://localhost & } || true
    docker run --interactive --tty --rm \
               --publish 80:80 \
               --mount type=bind,source=$(pwd),target=/elegant-git \
               ${eg_documents_image} preview
}

serve-docs() {
    generate-docs
    preview-docs
}
# docs workflows

repository() {
    info-text "Start container..."
    docker run -idt --rm --name repository --workdir /tmp/elegant-git-repo -v $PWD:/eg ${WORKER_IMAGE} bash
    info-text "Init repository..."
    docker exec -it repository bash -c "source /eg/tests/addons-repo.bash;source /eg/tests/addons-common.bash; repo-new"
    info-text "Install Elegant Git..."
    docker exec -it repository bash -c "
        cd /eg
        git config --global user.name \"Elegant Git\"
        git config --global user.email elegant.git@email.com
        git config --global core.editor vi
        git config --global elegant-git.acquired true
        ./install.bash /usr/local src
    "
    info-text "Ready! Enjoy experiments..."
    docker attach repository
}

# testing workflows
testing() {
    docker run -it --rm -v $PWD:/eg ${WORKER_IMAGE} .workflows/bats-pipeline.bash "$@"
}

__fail() {
    error-box $@
    exit 1
}

test-commands-docs() {
    (
        generate-docs
        git update-index --really-refresh
        git diff-index --quiet HEAD docs
    ) || __fail "'docs/commands.md' is not up to date. Please run './workflows generate-docs' and commit the changes."
}

test-docs-site() {
    {
        docker run --interactive --rm \
                   --mount type=bind,source=$(pwd),target=/elegant-git \
                ${eg_documents_image} build
    } || __fail "Unable to build the documentation site."
}

ci() {
    docker run --rm -v $PWD:/eg ${WORKER_IMAGE} .workflows/ci-pipeline.bash testing
    test-commands-docs
    test-docs-site
}

prepare-worker() {
    if [[ -z ${1} ]]; then
        error-text "Please specify a tag for Docker image (like '2')"
    fi
    docker build --no-cache -t beeshive/elegant-git-ci:${1} .
}

publish-worker() {
    if [[ -z ${1} ]]; then
        error-text "Please specify a tag for Docker image (like '2')"
    fi
    docker push beeshive/elegant-git-ci:${1}
}

robot() {
    # runs a
    local smart_testing_status=""
    local command_files=($(git ls-files --modified --other -- libexec/git-elegant*))

    for command_file in ${command_files[@]}; do
        local command_name=$(basename ${command_file})
        if ! test -f tests/${command_name}.bats; then continue; fi
        ( testing ${command_name} && info-text "'${command_file}' testing is passed." ) || {
            error-text "'${command_name}' testing is failed."
            smart_testing_status=failed
        }
    done
    local tests_files=($(git ls-files --modified --other -- tests/git-elegant*.bats))
    for test_file in ${tests_files[@]}; do
        local file_name=$(basename ${test_file})
        if [[ ${command_files[@]} =~ "${file_name/.bats/}" ]] ; then
            continue # already tested
        fi
        if ! test -f tests/${command_name}.bats; then continue; fi
        ( testing ${file_name} && info-text "'${file_name}' testing is passed.") || {
            error-text "'${file_name}' testing is failed."
            smart_testing_status=failed
        }
    done
    if test -z "${smart_testing_status}"; then
        info-text "Everything is great!"
    else
        error-text "Something should be improved!"
        exit 1
    fi
}
# testing workflows

usage() {
    cat <<MESSAGE
usage: ${BASH_SOURCE[0]} [command] [arg]...

Available commands:
  developing documentation
    prepare-docs-worker  builds a new '${eg_documents_image}' image
    publish-docs-worker  pushes the '${eg_documents_image}' image
    generate-docs        generates fresh commands documentation
    preview-docs         runs a site with the current documentation (http://localhost)
    serve-docs           runs 'generate-docs' and 'preview-docs'
  testing modifications
    prepare-worker       builds a new worker image
    publish-worker       pushes a new worker image
    testing              runs bats tests; accepts a optional pattern for tests
                         filtering ("${BASH_SOURCE[0]} testing work" run all tests
                         which have the word in the test name)
    test-commands-docs   checks if the commands docs are up to date
    test-docs-site       checks if the docs site can be built
    ci                   runs CI quality assessment workflow
    robot                runs tests for updated "libexec/git-elegant*" or
                         "tests/git-elegant*.bats" files
  other
    help                 prints this message
    repository           creates a git repository and installs Elegant Git within
MESSAGE
}

commands=(
    prepare-docs-worker
    publish-docs-worker
    generate-docs
    preview-docs
    serve-docs
    testing
    test-commands-docs
    test-docs-site
    usage
    robot
    repository
    ci
    prepare-worker
    publish-worker
)

main() {
    local command=${1}
    if [[ -z ${command} ]]; then
        question-text "Please select a command:"
        echo ""
        select any in ${commands[@]}; do
            command=${any}
            if test ${command} = testing; then
                question-text "Please give the tests pattern: "
                read args
            fi
            break
        done
    else
        shift
    fi
    info-box "Run:" ${command} ${args:-${@}}
    ${command} ${args:-${@}}
}

main ${@}
