#!/usr/bin/env bash
set -e

default() {
    case "$1" in
        "-a" | "--all")
            git diff --check
            git diff --cached --check
            ;;
        "-u" | "--unstaged")
            git diff --check
            ;;
        "-s" | "--staged")
            git diff --cached --check
            ;;
        *) git elegant check --all
            ;;
    esac
}
