#!/usr/bin/env bash
set -e

default() {
    _validate "$1" "Feature name"
    status=$(boxtee git stash save elegant-git)
    git elegant pull $MASTER
    boxtee git checkout -b "$1"

    if [[ "$status" =~ "Saved working directory" ]]; then
        boxtee git stash apply stash^{/elegant-git}
        boxtee git stash drop stash@{0}
    fi
}
