#!/usr/bin/env bash

_git_elegant() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    case "${prev}" in
        pull)
            local data=$(git branch | awk -F ' +' '! /\(no branch\)/ {print $2}')
            COMPREPLY=( $(compgen -W "${data}" ${cur}) )
            return 0 ;;
        push) 
            COMPREPLY=( $(compgen -W "$(git branch | grep \* | cut -d ' ' -f2)" ${cur}) )
            return 0 ;;
        *) ;;
    esac

    opts=($(git elegant commands))
    COMPREPLY=( $(compgen -W "${opts[*]}" -- ${cur}) )
}
