#!/usr/bin/env bash
set -e

default() {
    echo "feature"
    echo "pull"
    echo "push"
    echo "push-after-rebase"
    echo "rebase"
    echo "init"
    echo "acquire-repository"
    echo "add"
    echo "clear-local"
    echo "configure-repository"
    echo "check"
    echo "save"
    echo "amend"
}
