#!/usr/bin/env bash
set -e

default() {
    _validate "$1" "Feature name"
    status=$(git stash save elegant-git)
    git elegant pull $MASTER
    git checkout -b "$1"

    if [[ "$status" =~ "Saved working directory" ]]; then
        git stash apply stash^{/elegant-git}
        git stash drop stash@{0}
    fi
}
