#!/usr/bin/env bash
set -e

default() {
    case "$1" in
        "-a" | "--all")
            boxtee git diff --check
            boxtee git diff --cached --check
            ;;
        "-u" | "--unstaged")
            boxtee git diff --check
            ;;
        "-s" | "--staged")
            boxtee git diff --cached --check
            ;;
        *)  boxtee git elegant check --all
            ;;
    esac
}
