#!/usr/bin/env bash
# The plugin provides configuration for "acquired" logic that determines
# whether Elegant Git global configuration is applied or not.

acquired=("elegant-git.acquired" "true")

is-git-acquired() {
    # usage : is-git-acquired
    # result: 0 or 1
    if [[ "$(git config --global --get ${acquired[0]} || true)" == ${acquired[1]} ]]; then
        return 0
    fi
    return 1
}
