#!/usr/bin/env bash
# This plugin is responsible for handling default branches logic.
default_branch_key="elegant-git.default-branch"
default_branch_default="main"
default_branch_message="What is the default branch?"

DEFAULT_BRANCH=$(git config ${default_branch_key} || echo ${default_branch_default})
DEFAULT_UPSTREAM_REPOSITORY="origin"
DEFAULT_REMOTE_TRACKING_BRANCH="${DEFAULT_UPSTREAM_REPOSITORY}/${DEFAULT_BRANCH}"

freshest-default-branch() {
    # If there is a remote, the remote branch will have the latest version of changes.
    # Meanwhile, the local one can have non-fresh changes as `git fetch` doesn't update
    # the local branch.
    # usage: $(freshest-default-branch)
    if test -z "$(git remote)"
    then
        echo ${DEFAULT_BRANCH}
    else
        echo ${DEFAULT_REMOTE_TRACKING_BRANCH}
    fi
}
