#!/usr/bin/env bash
# This plugin is responsible for handling default branches logic.
default_branch_key="elegant-git.default-branch"
default_branch_default="master"
default_branch_message="What is the default branch?"

DEFAULT_BRANCH=$(git config ${default_branch_key} || echo ${default_branch_default})
DEFAULT_UPSTREAM_REPOSITORY="origin"
DEFAULT_REMOTE_TRACKING_BRANCH="${DEFAULT_UPSTREAM_REPOSITORY}/${DEFAULT_BRANCH}"
