#!/usr/bin/env bash
## This plugin is responsible for handling protected branches logic.
protected_branches_key="elegant-git.protected-branches"
protected_branches_default="main"
protected_branches_message="What are protected branches (split with space)?"

protected-branches() {
    # usage : protected-branches
    # result: "main other-branch"
    git config ${protected_branches_key} || echo ${protected_branches_default}
}

is-branch-protected() {
    # usage : is-branch-protected <my-branch-name>
    # result: 0 or 1
    _error-if-empty "${1}" "Please give a branch name."
    if [[ $(protected-branches) =~ ((^${1} )|(${1}$)|( ${1} )) ]]; then
        return 0
    fi
    return 1
}
