#!/usr/bin/env bash
# The plugin which allows running a given functions through different types
# (aka pre- and post-conditions).

has-changes() {
    # Check if a current index (HEAD) has staged or non-staged changes
    if git diff-index --quiet HEAD && git diff-index --cached --quiet HEAD; then
        return 1
    fi
    return 0
}

stash-pipe() {
    # Makes automatic stash and unstash if possible
    # usage:  stash-pipe <command> [args]...
    # The pipe behavior is tested based on `start-work` command. That's why you
    # have to add new tests in `git-elegant-start-work.bats` if you want to
    # check some specific cases.

    git update-index -q --really-refresh
    if has-changes; then
        local message="Elegant Git auto-stash: "
        message+="WIP in '$(git rev-parse --abbrev-ref HEAD)' branch "
        message+="on $(date "+%Y-%m-%dT%H:%M:%S")"
        git-verbose stash push --message "${message}"
    fi

    "${@}"

    if [[ -n ${message} ]]; then
        git update-index -q --really-refresh
        local stash=$(git stash list --grep="${message}" --format="%gd")
        if [[ -n ${stash} ]]; then
            git-verbose stash pop ${stash}
        fi
    fi
}

branch-pipe() {
    # Moves to the current branch after a command execution
    # usage: branch-pipe <command> [args]...
    local to=$(git rev-parse --abbrev-ref HEAD)
    "${@}"
    local now=$(git rev-parse --abbrev-ref HEAD)
    if [[ ! "${to}" == "${now}" ]]; then
        git-verbose checkout ${to}
    fi
}
