#!/usr/bin/env bash
# The plugin which allows running a given functions through different types
# (aka pre- and post-conditions).

stash-pipe() {
    # Makes automatic stash and unstash if possible
    # usage:  stash-pipe <command> [args]...

    git update-index -q --refresh
    if ! git diff-index --quiet HEAD --; then
        local message="Elegant Git auto-stash: "
        message+="WIP in '$(git rev-parse --abbrev-ref HEAD)' branch "
        message+="on $(date "+%Y-%m-%dT%H:%M:%S")"
        git-verbose stash push --message "${message}"
    fi

    "${@}"

    if [[ -n "${message}" ]]; then
        git update-index -q --refresh
        git-verbose stash pop $(git stash list --grep="${message}" --format="%gd")
    fi
}

branch-pipe() {
    # Moves to the current branch after a command execution
    # usage: branch-pipe <command> [args]...
    local to=$(git rev-parse --abbrev-ref HEAD)
    "${@}"
    local now=$(git rev-parse --abbrev-ref HEAD)
    if [[ ! "${to}" == "${now}" ]]; then
        git-verbose checkout ${to}
    fi
}
