#!/usr/bin/env bash
# The plugin that wraps the useful operations that describes a state of the repository.

is-there-active-rebase(){
    # Says if there is a rebase in progress.
    for location in rebase-merge rebase-apply; do
        if test -d $(git rev-parse --git-path ${location}); then
            return 0
        fi
    done
    return 1
}

rebasing-branch() {
    # Says a branch name that is rebasing now.
    # The output will be empty if there is no rebase in progress.
    for location in rebase-merge rebase-apply; do
        path=$(git rev-parse --git-path ${location})
        if test -d ${path}; then
            revision=$(<${path}/head-name)
            echo ${revision##refs/heads/}
            return 0
        fi
    done
}

last-tag() {
    # Seeks for the last created tag.
    git for-each-ref --sort "-version:refname" --format "%(refname:short)" refs/tags --count 1
}

is-there-upstream-for() {
    # usage: is-there-upstream-for <branch ref>
    git rev-parse --abbrev-ref ${1}@{upstream} >/dev/null 2>&1
}

are-there-remotes() {
    if test -z "$(git remote)"; then
        return 1
    fi
    return 0
}
