#!/usr/bin/env bash
# The plugin holds functions that convert one object into another.
# The most part of functions manipulates with strings.

branch-from-remote-branch() {
    # usage : echo $(branch-from-remote-branch origin/feature/a)
    # result: feature/a
    echo ${1#*/}
}

remote-from-remote-branch() {
    # usage : echo $(remote-from-remote-branch origin/feature/a)
    # result: origin
    echo ${1%%/*}
}
