#!/usr/bin/env bash

--prefix(){
    if [[ ! "init-repository clone-repository" =~ ${1} ]]; then
        git rev-parse --show-cdup 2>/dev/null
    fi
}

workflows-directory() {
    # usage: workflows-directory <location>
    if [[ ${1} == personal ]]; then
        echo "$(--prefix ${1}).git/.workflows"
    elif [[ ${1} == common ]]; then
        echo "$(--prefix ${1}).workflows"
    else
        error-text "Unknown workflows location: " ${1}
        exit 1
    fi
}

workflows-file() {
    # usage: workflows-file <location> <command> <type>
    echo "$(workflows-directory ${1})/${2}-${3}"
}

personal-workflows-file() {
    # usage: personal-workflows-file <comand> <type>
    workflows-file personal ${1} ${2}
}

common-workflows-file() {
    # usage: common-workflows-file <comand> <type>
    workflows-file common ${1} ${2}
}
