#!/usr/bin/env bash
set -e

default() {
    local PATTERN=${1}
    _error-if-empty "${PATTERN}" "Please provide a branch name or its part."
    boxtee git fetch --all
    local REMOTE_BRANCHES=(
            $(git for-each-ref --format='%(refname:strip=2)' refs/remotes/** | grep "${PATTERN}")
        )
    if [[ ${#REMOTE_BRANCHES[@]} > 1 ]]; then
        echo "The following branches are found:"
        for branch in ${REMOTE_BRANCHES[@]}; do
            echo " - ${branch}"
        done
        box "Please re-run the command with concrete branch name from the list above!"
        exit 43
    fi
    if [[ ${#REMOTE_BRANCHES[@]} = 1 ]]; then
        local REMOTE=${REMOTE_BRANCHES[0]}
        local LOCAL=${2}
        if [[ -z ${LOCAL} ]]; then
            LOCAL=$(branch-from-remote-reference ${REMOTE})
        fi
        boxtee git checkout -B ${LOCAL} ${REMOTE}
    else
        box "There is no branch that matches the '${PATTERN}' pattern."
        exit 43
    fi
}
