#!/usr/bin/env bash
set -e

command-purpose() {
    cat <<MESSAGE
Configures current repository.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant acquire-repository
MESSAGE
}

command-description() {
    cat<<MESSAGE
Applies the "basics", "standards", and "aliases" configurations to the current
Git repository using \`git config --local\`.

To find out what will be configured, please visit
${__site}/en/latest/configuration/
MESSAGE
}

default() {
    source ${BINS}/plugins/configuration
    if $(is-acquired) ; then
        basics-configuration --local user_name user_email
        aliases-removing --local
    else
        basics-configuration --local user_name user_email core_editor
        standards-configuration --local \
          core_comment \
          apply_whitespace \
          fetch_prune \
          fetch_pruneTags \
          core_autocrlf_darwinlinux \
          core_autocrlf_windows pull_rebase \
          rebase_autoStash \
          credential_helper_darwin
        aliases-removing --local
        aliases-configuration --local $(git elegant show-commands)
    fi
}
