#!/usr/bin/env bash

command-purpose() {
    cat <<MESSAGE
Prints a release log between two refs.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant show-release-notes [<layout>] [<from-ref>] [<to-ref>]
MESSAGE
}

command-description() {
    cat<<MESSAGE
Prints commit titles of the commits between the given refs ordered from oldest
to newest.

A \`layout\` defines a formatting for the output - \`simple\` or \`smart\`. The
\`simple\` layout prints the messages as a plain text (the default one) while
the \`smart\` one prints the messages in an adopted form for a Git hosting
service. If the hosting service is unknown, the default layout is used.

For Github, the \`smart\` layout prints an HTML that includes HTML links to the
commits and issues if possible.

A \`from-ref\` is a ref to start work from (not included to the output). By
default, it is the last tag. If there are no tags, the command uses the first
commit in HEAD.

A \`to-ref\` is a ref to stop work with (included to the output). By default,
it is a HEAD.

Approximate command's output is
\`\`\`bash
==>> git elegant show-release-notes
Release notes
- Add \`show-release-notes\` command
- Add \`release-work\` command
\`\`\`
MESSAGE
}

--github-release-notes() {
    local diapason="${1}"
    local changelog="github-release-notes"
    echo "<h3>Release notes</h3>" > ${changelog}
    local url=$(git remote get-url origin)
    local repository=""
    [[ ${url} =~ "github.com/" ]] && repository=${url##*github.com/}
    [[ ${url} =~ "github.com:" ]] && repository=${url##*github.com:}
    repository=${repository%%.git}

    for hash in $(git log ${diapason} --format=%H --reverse); do
        local issues=$(git show -s --pretty=%B ${hash} | grep "#")
        [[ ! -z ${issues} ]] && issues=" [${issues}]"
        local subject=$(git show -s --pretty=%s ${hash})
        echo "<li> <a href=\"https://github.com/${repository}/commit/${hash}\">${subject}</a>${issues}</li>" >> ${changelog}
    done
    cat ${changelog}
    remove-file ${changelog}
}

--simple-release-notes() {
    local diapason="${1}"
    local changelog="simple-release-notes"
    echo "Release notes" > ${changelog}
    for hash in $(git log ${diapason} --format=%H --reverse); do
        echo "- $(git show -s --pretty=%s ${hash})" >> ${changelog}
    done
    cat ${changelog}
    remove-file ${changelog}
}

default() {
    source ${BINS}/plugins/state
    local layout=${1:-simple}
    local first=${2:-$(last-tag)}
    local second=${3:-@}
    local diapason=${first}...${second}
    if [[ ${first} == all-commits ]] || [[ -z ${first} ]]; then
        diapason=${second}
    fi
    case ${layout} in
        simple)
            --simple-release-notes ${diapason}
            ;;
        smart)
            if [[ "$(git remote get-url origin)" =~ ((https://)|(git@))github.com ]]; then
                --github-release-notes ${diapason}
            else
                --simple-release-notes ${diapason}
            fi
            ;;
        *)  error-text "A layout can be 'simple' or 'smart'! '${layout}' layout is not supported."
            exit 43;;

    esac
}
