#!/usr/bin/env bash

command-purpose() {
    cat <<MESSAGE
Shows configured workflows in the repository.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant show-workflows
MESSAGE
}

command-description() {
    cat<<MESSAGE
Shows all personal and common workflows files that are available in the
repository.

Personal workflows are located in \`.git/.workflows\` directory and common ones
are in \'.workflows\` relatively to the repository root directory.

Approximate command's output is
\`\`\`bash
==>> git elegant show-workflows
.git/.workflows/accept-work-after
.workflows/amend-work-ahead
.workflows/amend-work-after
.workflows/release-work-after
.workflows/save-work-ahead
.workflows/save-work-after
....
\`\`\`
MESSAGE
}

--list() {
    if test -e "${1}" ; then
        echo "${1}"
    fi
}

default() {
    for command in $(git elegant show-commands); do
        --list $(personal-workflows-file ${command} ahead)
        --list $(personal-workflows-file ${command} after)
        --list $(common-workflows-file ${command} ahead)
        --list $(common-workflows-file ${command} after)
    done
}
