#!/usr/bin/env bash
set -e

default() {
    echo "acquire-repository"
    echo "clone-repository"
    echo "init-repository"
    echo "start-work"
    echo "save-work"
    echo "deliver-work"
    echo "accept-work"
    echo "obtain-work"
    echo "clear-local"
    echo "commands"
    echo "amend-work"
}
