#!/usr/bin/env bash
set -e

default() {
    _error-if-empty "$1" "Please give a name for the new branch."
    status=$(boxtee git stash save elegant-git)
    git elegant obtain-work ${MASTER}
    boxtee git checkout -b "$1"

    if [[ "$status" =~ "Saved working directory" ]]; then
        boxtee git stash apply stash^{/elegant-git}
        boxtee git stash drop stash@{0}
    fi
}
