#!/usr/bin/env bash
set -e

command-purpose() {
    cat <<MESSAGE
Amends the last commit.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant amend-work
MESSAGE
}

command-description() {
    cat<<MESSAGE
Amends the last commit by incorporating the current state of the repository.
The command provides full control of what modifications should be included by
starting an interactive commit process.

The command doesn't allow to modify the history of the default development branch.

Approximate commands flow is
\`\`\`bash
==>> git elegant amend-work
git add --interactive
git diff --cached --check
git commit --amend
\`\`\`
MESSAGE
}

default(){
    local BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if [[ "$BRANCH" == "master" ]]; then
        error-box "No commits to 'master' branch. Please read more on ${__site}"
        error-box "Try 'git elegant start-work' prior to retrying this command."
        exit 42
    fi
    git-verbose add --interactive
    git-verbose diff --cached --check
    git-verbose commit --amend
}
