#!/usr/bin/env bash
set -e

_core_comment_char_key="core.commentChar"
_core_comment_char_default="|"
_core_comment_char_message="commit message won't start with"

_user_name_key="user.name"
_user_name_default=$(git config "$_user_name_key" || echo '')
_user_name_message="your user name"

_user_email_key="user.email"
_user_email_default=$(git config "$_user_email_key" || echo '')
_user_email_message="your user email"

_apply_whitespace_key="apply.whitespace"
_apply_whitespace_default="fix"
_apply_whitespace_message="whitespace issues on patching"

_alias_key="alias."
_alias_default="yes"
_alias_message="add git aliases for all 'elegant git' commands"


_configure() {
    FUNCTIONS=$@
    for f in ${FUNCTIONS[@]}; do
        unset answer
        while [ -z "$answer" ]; do
            # ask a question
            message=$(eval "echo -n \$${f}_message")
            echo -n "$message"
            default=$(eval "echo -n \$${f}_default")
            if [ -n "$default" ]; then echo -n " [$default]"; fi
            echo -n ": "
            # run git config
            read answer
            answer=${answer:-$default}
            if [ "$f" = "_alias" ]; then
                if [ "$answer" = "$_alias_default" ]; then
                    for com in $(git elegant commands); do
                        alias="e${com}"
                        command="elegant $com"
                        boxtee git config --local $(eval "echo -n \$${f}_key\$alias") "$command"
                    done
                fi
            else
                if [ -n "${answer}" ]; then
                    boxtee git config --local $(eval "echo -n \$${f}_key") "$answer"
                fi
            fi
        done
    done
}

default() {
      _configure _user_name _user_email _core_comment_char _apply_whitespace
}
