#!/usr/bin/env bash
set -e

command-purpose() {
    cat <<MESSAGE
Prints available Elegant Git commands.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant commands
MESSAGE
}

command-description() {
    cat<<MESSAGE
Displays all available commands. This is useful for completion functions as well
as for other cases when you need iteration over the available commands.

Approximate commands flow is
\`\`\`bash
==> git elegant commands
echo <command>
echo ...
\`\`\`
MESSAGE
}

default() {
    echo "acquire-repository"
    echo "clone-repository"
    echo "init-repository"
    echo "start-work"
    echo "save-work"
    echo "deliver-work"
    echo "accept-work"
    echo "obtain-work"
    echo "clear-local"
    echo "commands"
    echo "amend-work"
}
