#!/usr/bin/env bash
set -e

command-purpose() {
    cat <<MESSAGE
Prints HEAD state.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant show-work
MESSAGE
}

command-description() {
    cat<<MESSAGE
Prints HEAD state by displaying local and remote-tracking (if available) refs,
commits that aren't in the default development branch, uncommitted
modifications, and available stashes.

Approximate commands flow is
\`\`\`bash
==>> git elegant show-work
git log --oneline master..@
git status --short
git stash list
\`\`\`
MESSAGE
}

default(){
    source ${BINS}/plugins/configuration-default-branches
    local branch=$(git rev-parse --abbrev-ref @)
    info-text ">>> Branch refs:"
    info-text "local:  ${branch}"
    local upstream=$(git rev-parse --abbrev-ref ${branch}@{upstream} 2>/dev/null || echo)
    if [[ -n ${upstream} ]]; then
        info-text "remote: ${upstream}"
    fi
    info-text ""
    local latest_changes=$(freshest-default-branch)
    if [[ -n $(git rev-list ${latest_changes}..${branch}) ]]; then
        info-text ">>> New commits (comparing to '${latest_changes}' branch):"
        git log --oneline ${latest_changes}..${branch}
        info-text ""
    fi
    if [[ -n $(git status --short) ]]; then
        info-text ">>> Uncommitted modifications:"
        git status --short
        info-text ""
    fi
    if [[ -n $(git stash list) ]]; then
        info-text ">>> Available stashes:"
        git stash list
        info-text ""
    fi
}
