#!/usr/bin/env bash
set -e

default() {
    echo "clone-repository"
    echo "start-work"
    echo "save-work"
    echo "deliver-work"
    echo "accept-work"
    echo "pull"
    echo "init"
    echo "add"
    echo "clear-local"
    echo "configure-repository"
    echo "commands"
}
