#!/usr/bin/env bash
set -e

command-purpose() {
    cat <<MESSAGE
Clones a repository and configures it.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant clone-repository <repository>
MESSAGE
}

command-description() {
    cat<<MESSAGE
Clones a repository into a new directory and runs its configuration.

Approximate commands flow is
\`\`\`bash
==> git elegant clone-repository git@github.com:bees-hive/elegant-git.git
git clone git@github.com:bees-hive/elegant-git.git
cd elegant-git
git elegant acquire-repository
\`\`\`
MESSAGE
}

default() {
    _error-if-empty "$1" "Cloneable URL is not set."
    git-verbose clone "$1"
    cd $(basename -s .git $1)
    git elegant acquire-repository
}
