#!/usr/bin/env bash

command-purpose() {
    cat <<MESSAGE
Edits a given workflows file.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant polish-workflow <file>
MESSAGE
}

command-description() {
    cat<<MESSAGE
Opens a given workflow file in the default text editor. If given file is not
present, the command raises an error.

Approximate commands flow is
\`\`\`bash
==>> git elegant polish-workflow .workflows/show-work-ahead
vim .workflows/show-work-ahead
\`\`\`
MESSAGE
}

default() {
    _error-if-empty "${1}" "Please specify a workflow file name"
    if test -e ${file}; then
        $(git config core.editor) ${file}
    else
        error-text "The '${file}' file does not exist."
        exit 43
    fi
}
