#!/usr/bin/env bash
set -e

default() {
    echo "This command is deprecated. It will be removed soon."
    case "$1" in
        "-a" | "--all")
            boxtee git diff --check
            boxtee git diff --cached --check
            ;;
        "-u" | "--unstaged")
            boxtee git diff --check
            ;;
        "-s" | "--staged")
            boxtee git diff --cached --check
            ;;
        *)  git elegant check --all
            ;;
    esac
}
