#!/usr/bin/env bash
set -e


default() {
    local WORK=${1}
    _error-if-empty "${WORK}" "Please give a name of remote branch (like 'origin/123')."
    local WORK_BRANCH="__eg"
    boxtee git fetch --all --tags
    boxtee git checkout -b ${WORK_BRANCH} ${WORK}
    boxtee git rebase ${RMASTER}
    # @todo #137 Alternative flows of `accept-work`
    #  If this command is executed with `${WORK_BRANCH}` and
    #  1. `git rebase` is in progress, it has to run `git rebase --continue` prior working with
    #  `${MASTER}` branch.
    #  2. `git rebase` is completed (history of `${WORK_BRANCH}` and `${RMASTER}` are different),
    #  just work with `${MASTER}` branch.
    boxtee git checkout ${MASTER}
    boxtee git merge --ff-only ${WORK_BRANCH}
    boxtee git push ${REMOTE_NAME} ${MASTER}:${MASTER}
    boxtee git branch --delete ${WORK_BRANCH}
    boxtee git push ${REMOTE_NAME} --delete $(echo "${1}" | sed -e "s|${REMOTE_NAME}/||")
}
