#!/usr/bin/env bash
set -e

command-purpose() {
    cat <<MESSAGE
Prints available Elegant Git commands.
MESSAGE
}

command-synopsis() {
    cat <<MESSAGE
usage: git elegant show-commands
MESSAGE
}

command-description() {
    cat<<MESSAGE
Displays all available Elegant Git commands. This is useful for completion
functions as well as for other cases when you need iteration over the available
commands.

Approximate command's output is
\`\`\`bash
==>> git elegant show-commands
start-work
show-commands
....
\`\`\`
MESSAGE
}

default() {
    local pattern="git-elegant-*"
    for command_path in $(ls -1 ${BINS}/${pattern}); do
        local command_file=$(basename ${command_path})
        echo ${command_file#${pattern}}
    done
}
