name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >-
          Thank you for submitting the first issue! 
          You're making a great contribution to improve Elegant Git.
        pr-message: >-
          Thank you for making the first contribution!
          We do enjoy your efforts in making Elegant Git better!
