name: Haskell Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.4'
        enable-stack: true
        stack-version: '2.7.3'
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-ghcup
      with:
        path: ~/.ghcup
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install hlint
      run:
        wget -O /tmp/hlint-3.3.6.tar.gz https://github.com/ndmitchell/hlint/releases/download/v3.3.6/hlint-3.3.6-x86_64-linux.tar.gz
    - name: Extract tgz
      uses: ihiroky/extract-action@v1
      with:
        file_path: /tmp/hlint-3.3.6.tar.gz
        extract_dir: /tmp
    - name: Install hlint
      run:
        cp /tmp/hlint-3.3.6/hlint ~/.ghcup/bin/hlint
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml', 'elegant-git.cabal', 'stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Run hlint
      run: hlint .
    - name: Build dependencies
      run: stack build --no-haddock --only-dependencies --fast --pedantic
    - name: Run tests
      run: stack test --fast --pedantic

