name: Haskell Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.0.2' # Exact version of ghc to use
        enable-stack: true
        stack-version: '2.7.3'
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-ghcup
      with:
        path: ~/.ghcup
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml', 'elegant-git.cabal', 'stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build dependencies
      run: stack build --no-haddock --only-dependencies --fast --pedantic
    - name: Run tests
      run: stack test --fast --pedantic

