name: Quality pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run development pipeline
      run: docker run --rm -v $PWD:/eg beeshive/elegant-git-ci:3 ./quality-pipeline.bash testing
